services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - '/var/data'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
