services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms-sql
    # restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password@1
    ports:
      - 127.0.0.1:1433:1433
    volumes:
      - sqlserver_volume:/var/opt/mssql

volumes:
  sqlserver_volume:
