services:
  postgres:
    image: postgres:17.4
    container_name: postgresql
    # restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.1
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 127.0.0.1:15432:80
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_volume:
  pgadmin_volume:
