services:
  sqlpad:
    image: sqlpad/sqlpad:7.5
    container_name: sqlpad
    environment:
      SQLPAD_ADMIN: admin@sqlpad.com
      SQLPAD_ADMIN_PASSWORD: admin
    ports:
      - 127.0.0.1:4000:3000
    volumes:
      - sqlpad_volume:/var/lib/sqlpad

volumes:
  sqlpad_volume:
