services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    # restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password@1
    ports:
      - 1433:1433
    volumes:
      - mssql_volume:/var/opt/mssql

volumes:
  mssql_volume:
