services:
  redis:
    image: redis/redis-stack:7.4.0-v3
    container_name: redis-stack
    ports:
      - 6378:8001 # connects to UI
      - 6379:6379
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
