services:
  zoo1:
    image: zookeeper:3.9.4
    container_name: zoo1
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - zoo1_data:/data

  zoo2:
    image: zookeeper:3.9.4
    container_name: zoo2
    restart: unless-stopped
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - zoo2_data:/data

  zoo3:
    image: zookeeper:3.9.4
    container_name: zoo3
    restart: unless-stopped
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - zoo3_data:/data

  zoo-navigator:
    image: elkozmon/zoonavigator:1.1.4
    container_name: zoo-navigator
    restart: unless-stopped
    ports:
      - 9000:9000
    depends_on:
      - zoo1
      - zoo2
      - zoo3

volumes:
  zoo1_data:
  zoo2_data:
  zoo3_data:
