services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./docker.env
    ports:
      - "3000:3000"
    volumes:
      - outline-data-local:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7-alpine
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - redis-data-local:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:15-alpine
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - database-data-local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d outline"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'

volumes:
  outline-data-local:
  redis-data-local:
  database-data-local:
